name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        # Remove LFS since we're using S3 now

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run tests with coverage
        run: npm run test:coverage

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        # Remove LFS since we're using S3 now
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Cache S3 downloaded sref images only (metadata is committed)
      - name: Cache S3 sref images
        uses: actions/cache@v4
        id: s3-cache
        with:
          path: src/data/srefs/*/images
          key: s3-srefs-${{ hashFiles('src/data/srefs/**/meta.yaml') }}
          restore-keys: |
            s3-srefs-

      # Cache S3 downloaded public assets only (text files are committed)
      - name: Cache S3 public assets
        uses: actions/cache@v4
        id: s3-public-cache
        with:
          path: |
            public/*.png
            public/*.ico
          key: s3-public-${{ hashFiles('public/robots.txt', 'public/site.webmanifest') }}
          restore-keys: |
            s3-public-

      # Cache Astro processed images and build artifacts
      - name: Cache Astro processed images
        uses: actions/cache@v4
        id: astro-cache
        with:
          path: |
            dist/_astro
            node_modules/.astro
          key: astro-images-${{ hashFiles('src/data/srefs/**/*', 'package-lock.json') }}
          restore-keys: |
            astro-images-

      - name: Build with S3 sync and CDN
        env:
          AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
          AWS_REGION: us-west-2
          PUBLIC_USE_CDN: 'true'
          PUBLIC_CLOUDFRONT_DOMAIN: ${{ vars.CLOUDFRONT_DOMAIN }}
          S3_CACHE_HIT: ${{ steps.s3-cache.outputs.cache-hit }}
          S3_PUBLIC_CACHE_HIT: ${{ steps.s3-public-cache.outputs.cache-hit }}
          ASTRO_CACHE_HIT: ${{ steps.astro-cache.outputs.cache-hit }}
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4